BolShpping/Controllers/WishListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BolShpping.Models.BLL;
using BolShpping.Models.DAL;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace BolShpping.Controllers
{
    public class WishListController : Controller
    {
        private readonly MyContext _context;

        public WishListController( MyContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            List<Favourite> cart = new List<Favourite>();

            var session = HttpContext.Session.GetString("ShoppingFavourite");

            if (session != null)
            {
                cart = JsonConvert.DeserializeObject<List<Favourite>>(session);
            }

            return View(cart);
        }


        [HttpPost]
        public async Task<IActionResult> AddBasket(int id, int quantity = 1)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return Json(new
                {
                    status = 400
                });
            }
            Cart cart = null;
            if (id != 0)
            {
                var carts = await _context.Carts.ToListAsync();

                foreach (var item in carts)
                {
                    if (item.ProductId == id)
                    {
                        return Json(new
                        {
                            status = 404,
                            basket = item
                        });
                    }
                }
                var product = await _context.Products.FindAsync(id);
                var productQuantity = quantity * product.Price;
                cart = new Cart()
                {
                    Product = product,
                    ProductId = id,
                    Quantity = quantity,
                    SubTotalPrice = productQuantity
                };
                await _context.Carts.AddAsync(cart);
                await _context.SaveChangesAsync();
            }

            return Json(
                new
                {
                    basket = cart,
                    status = 200

                }
            );
        }

        //[HttpPost]
        //public IActionResult RemoveBasket(int id)
        //{

        //    var session = HttpContext.Session.GetString("ShoppingFavourite");
        //    if (session != null)
        //    {
        //        _httpContext.Session.Remove(session);
        //        return Json(new
        //        {
        //            status = 200
        //        });
        //    }
        //    //var cart = await _context.Carts.FindAsync(id);

        //    //_context.Carts.Remove(cart);
        //    //await _context.SaveChangesAsync();
        //    return Json(new
        //    {
        //        status = 400
        //    });

        //}
    }
}

BolShpping/Views/WishList/Index.cshtml
@using BolShpping.Models.BLL
@model List<Favourite>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- breadcrumb-area start -->
<div class="breadcrumb-area breadcramb-bg ptb-80">
    <div class="container">
        <div class="row">
            <div class="col">
                <h2 class="breadcrumb-title">Wish List</h2>
                <ul class="breadcrumb-list">
                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                    <li class="breadcrumb-item active">Wish List</li>
                </ul>
            </div>
        </div>
    </div>
</div>
@{
    decimal totalCount = 0;
    decimal productCount = 0;
}
<!-- breadcrumb-area end -->
<!-- main-content-warpper start -->
<div class="main-content-warpper pt-80">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <form action="#">
                    <div class=" table-content table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    @*<th class="plantmore-product-remove">remove</th>*@
                                    <th class="plantmore-product-thumbnail">images</th>
                                    <th class="cart-product-name">Product</th>
                                    <th class="plantmore-product-price">Unit Price</th>
                                    <th class="plantmore-product-stock-status">Stock Status</th>
                                    <th class="plantmore-product-add-cart">add to cart</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model.Count == 0)
                                {
                                    <tr >
                                        <td colspan="5">
                                            <div class="alert alert-danger" role="alert">
                                                Sevimlilərdə məhsul əlavə edilməyib!
                                            </div>
                                        </td>
                                    </tr>
                                }
                                else
                                {
                                    @foreach (var item in Model)
                                    {
                                        <tr data-id="@item.Product.Id">
                                            @*<td class="plantmore-product-remove"><a  class="btn-cart-remove"><i class="fa fa-times"></i></a></td>*@
                                            <td class="plantmore-product-thumbnail"><a href="#"><img width="150" height="150" alt="" src="~/img/@_context.ProductImages?.Where(pi => pi.ProductId == item.ProductId).FirstOrDefault().ImageCode"></a></td>
                                            <td class="plantmore-product-name">@item.Product.Name<a href="#"></a></td>
                                            <td class="plantmore-product-price"><span class="amount">$@item.Product.Price</span></td>
                                            <td class="plantmore-product-stock-status"><span class="in-stock">in stock</span></td>
                                            <td class="plantmore-product-add-cart"><a asp-controller="WishList" asp-action="AddBasket" asp-route-id="@item.Product.Id" class="addCart" data-id="@item.Product.Id">add to cart</a></td>
                                        </tr>
                                    }
                                }


                            </tbody>
                        </table>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- main-content-warpper end -->
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script>
    $(document).on("click", ".addCart", function (e) {
        e.preventDefault();
        let id = this.getAttribute("data-id");
        console.log(id)
        let quantity = 1;
        console.log(quantity)


        $.ajax({
            url: "/WishList/AddBasket/",
            method: "POST",
            data: { id: id, quantity: quantity },
            dataType: "json",
            success: function myfunction(response) {
                console.log(response.status)

                if (response.status === 200) {
                    swal({
                        title: "Basket",
                        text: "Məhsulunuz səbətiniz-ə əlavə olundu",
                        icon: "success",
                    });
                    setTimeout(function () { location.reload(); }, 1700);

                }
                else if (response.status === 404) {
                    swal({
                        title: "Basket",
                        text: "Bu Məhsul artıq səbətinizdə var",
                        icon: "warning",
                    });
                }
                else if (response.status === 400) {
                    swal({
                        title: "Basket",
                        text: "Zəhmət olmasa qeydiyyatdan kecin",
                        icon: "warning",
                    });
                }

            }

        })
    })
</script>

<script>
    $(document).ready(function () {
        $(document).on("click", "a.btn-cart-remove", function (e) {
            e.preventDefault();
            console.log(this.parentElement.parentElement.getAttribute("data-id"))
            let id = this.parentElement.parentElement.getAttribute("data-id")
            //let id = $(this).parent().parent().data("id");
            console.log(id)

            $.ajax({
                url: "/WishList/RemoveBasket/" + id,
                method: "POST",
                dataType: "json",
                success: function (response) {
                    if (response.status == 200) {
                        swal({
                            title: "Basket",
                            text: "Məhsulunuz səbətinizdən silindi",
                            icon: "success",
                        });
                    }
                    
                    

                    setTimeout(function () { location.reload(); }, 1700);
                }

            })
        })
    })
</script>